library(FimoClient)
FIMO_HOST <- "localhost"
FIMO_PORT <- 5000
fc <- FimoClient(FIMO_HOST, FIMO_PORT, quiet=FALSE)
sequence <- list(cherry="CGCTGACCTTTTATAATCCTTTTTTTTTTTTTTCACATGTTTCAATTTGCGCCAGCTTATCCAAAAAGTGAGTCATTCATCTACTAATCATGATTTTCGGGATTCTGCCAATGAGTAACCACCACAAGAACGAACAAATAAT")
requestMatch(fc, sequence, pvalThreshold=0.0011)

