PORT=5560
FIMO="$(HOME)/meme/bin/fimo"
PYTHON_SCRIPT=$(HOME)/github/fimoService/server/runFimoServer.py
PYTHON=$(HOME)/anaconda3/bin/python
PYTHON_KHALEESI=$(HOME)/anaconda3/bin/python3

# FIMO="/Users/paul/meme/bin/fimo"
MOTIFS="../pfms/jaspar2018.hocomoco.human.meme"

start:
	$(PYTHON) $(PYTHON_SCRIPT) $(PORT) $(FIMO) $(MOTIFS)&
#	python -i runFimoServer.py $(PORT) $(FIMO) $(MOTIFS)
