PORT=5558
FIMO="/Users/paul/meme/bin/fimo"
#MOTIFS="/Users/paul/s/work/priceLab/cory/footprintWorkflow/JASPAR_CORE_plus_seth.meme"
#MOTIFS="../pfms/JASPAR_CORE_plus_seth.meme"
#MOTIFS="../pfms/MA0073.1.meme"
#MOTIFS="../pfms/jaspar2018.hocomoco.human.meme"
MOTIFS="../pfms/rreb1.human.meme"

start:
	python -i runServer.py $(PORT) $(FIMO) $(MOTIFS)
