PORT=5558
FIMO="/users/pshannon/meme/bin/fimo"
MOTIFS="../pfms/fli1.klf1.human.meme"

start:
	python -i runFimoServer.py $(PORT) $(FIMO) $(MOTIFS)


unitTests:
	python -i runFimoServer.py 5000 $(FIMO) ../pfms/human-jaspar2018-hocomoco-swissregulon.meme
        #rreb1.human.meme

